---
# Copyright (C) 2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Include tasks based on download filetype
  ansible.builtin.include_tasks:
    file: "setup-{{ kubectl_download_filetype | lower }}.yml"
